### ISSUE TITLE
Ender 3 pro

### ISSUE THREAD

**Issue by alex7919** [Jumbo125/Ender-3-Max-Marlin-2.0.x-4.2.2-and-4.2.7-board#1]
Is it possible to make the same for the Ender 3 Pro?

**Comment by Jumbo125** [comment]
I created it for some months. 
I'm Not Up to Date but If you can tell me some Updates.

**Comment by alex7919** [comment]
I wanted the same firmware for my Ender 3 pro, your firmware works great only my printer is smaller than the ender 3 max and so this mesh or biliniar leveling is not possible. I've been trying for days with visual studios but I only get the error message with g++.exe

**Comment by Jumbo125** [comment]
There is a marlin version for Ender 3 Pro avaible.
But i didn't try it, because i don't have a ender pro 3

This version is from another user, and i don't know how he set up other details like mesh bed, stop, change filament and more.

If you want, i can try to setup my version of marlin for your ender 3 pro.  If you want this, please ell me, which board you have. 4.2.2 or 4.2.7?

**Comment by alex7919** [comment]
I thank you so much, I have the 4.2.2 board

**Comment by Jumbo125** [comment]
okay. so i think you want a version from my settings. i will create it. 
but i can't  give any warranty that it work. you need to try it.

**Comment by alex7919** [comment]
That's OK

**Comment by Jumbo125** [comment]
Whitch driver do you have? TMC 2208 or TMC 2209 or other? A4988

**Comment by alex7919** [comment]
A4988
Sorry for the late reply But it was already late in Germany

**Comment by Jumbo125** [comment]
no problem. i'm in austria. We have the same timezone ;-)
I create a abin file for your stepper-driver.
You can test it out. all other settings are like my Ender 3 MAx verison.

**Comment by Jumbo125** [comment]
Please let me know, how it works, please!

**Comment by alex7919** [comment]
it works very great
25 points for leveling and corner-leveling
richtig geil
Ender 3 Pro 4.2.2 Board

**Comment by Jumbo125** [comment]
super. danke!

**Comment by Jumbo125** [comment]
dann kann ich das "not tested entfernern"?

**Comment by alex7919** [comment]
Ich habe jetzt zwei Objekte gedruckt und auch das Bedleveling getestet, funktioniert einwandfrei
Testet and great
